import { Account, AssetCategoryItem, SevaType, TempleAsset, TempleProfile, User, TempleEvent, FinancialYearPeriod } from '../types/accounting';

export const DEFAULT_ASSET_CATEGORIES: AssetCategoryItem[] = [
  {
    id: 'cat-jwl',
    code: 'SACRED_JEWELRY',
    name: 'Sacred Gold & Silver Jewels (Abharana)',
    nameHindi: 'स्वर्ण एवं रजत आभूषण',
    description: 'Deity crowns, gold kavacham, silver harams & precious ornaments',
    icon: '👑',
    isActive: true,
    isSystem: true,
  },
  {
    id: 'cat-lnd',
    code: 'LAND_PROPERTY',
    name: 'Temple Lands & Leased Properties',
    nameHindi: 'भूमि एवं भवन सम्पत्ति',
    description: 'Agricultural Patta lands, survey numbers, commercial shops & mandapams',
    icon: '🏛️',
    isActive: true,
    isSystem: true,
  },
  {
    id: 'cat-eqp',
    code: 'SANCTUM_EQUIPMENT',
    name: 'Sanctum Vahanas & Sacred Equipment',
    nameHindi: 'वाहन एवं मन्दिर उपकरण',
    description: 'Teakwood Garuda Vahana, procession chariots, brass bells & lamps',
    icon: '🪔',
    isActive: true,
    isSystem: true,
  },
  {
    id: 'cat-kit',
    code: 'KITCHEN_INVENTORY',
    name: 'Annadanam Kitchen Mega Cookware',
    nameHindi: 'अन्नदान रसोई के बर्तन',
    description: 'Heavy brass cooking cauldrons, boilers, grinders and dining utensils',
    icon: '🍲',
    isActive: true,
    isSystem: true,
  },
  {
    id: 'cat-cow',
    code: 'GOSHALA_CATTLE',
    name: 'Kamadhenu Goshala Cattle & Livestock',
    nameHindi: 'गौशाला गौमाता एवं बछड़े',
    description: 'Desi Gir cows, calves, and livestock for deity abhishekam milk',
    icon: '🐮',
    isActive: true,
    isSystem: true,
  },
];



export const DEFAULT_TEMPLE_PROFILE: TempleProfile = {
  id: 'temple-001',
  name: 'Shri Siddeswar Temple, Hodalur',
  deity: 'LORD SHIVA',
  trustName: 'Shri Siddeswar Temple Charitable Trust',
  registrationNo: 'TR-2018-8849',
  panNumber: 'AAATL9948P',
  address: 'Hodalur Sanctum Marg, Taluk Aland',
  city: 'Hodalur',
  state: 'Karnataka',
  pincode: '585316',
  phone: '+91 98765 43210',
  email: 'accounts@shrisiddeswar.org',
  upiVpa: 'siddeswartemple@sbi',
  bankAccountName: 'Shri Siddeswar Temple Trust',
  bankAccountNumber: '38992019482',
  bankIfsc: 'SBIN0004052',
  bankName: 'State Bank of India',
};

export const DEFAULT_USERS: User[] = [
  { 
    id: 'usr-trustee-siddeswar', 
    name: 'Dr. K. V. Sharma (Trustee)', 
    username: 'trustee', 
    password: 'trustee123', 
    role: 'trustee', 
    counterName: 'Trustee Board', 
    pin: '3456', 
    phone: '+91 98765 43210',
    isActive: true,
    createdAt: '2025-01-10'
  },
];

export const DEFAULT_SEVA_TYPES: SevaType[] = [
  // 1. Grand Festivals & Annual Utsavas (Primary Festival Events)
  {
    id: 'seva-shiva-1',
    code: 'EVT-SH-01',
    name: 'Maha Shivaratri Mahotsava 2026',
    defaultAmount: 2501,
    deity: 'Lord Shiva / Someshwara',
    category: 'FESTIVAL_EVENT',
    isActive: true,
    isSpecialEvent: true,
    periodLabel: 'Annual Mahotsava (Feb / Mar)',
    budgetEstimated: 2500000,
    description: '4-Prahar Maha Abhishekam, Rudra Homa, Bilva Archana & Jagaran Utsavam',
  },
  {
    id: 'seva-ratha-1',
    code: 'EVT-RT-01',
    name: 'Annual Brahmarathotsava (Car Festival) 2026',
    defaultAmount: 2001,
    deity: 'Utsava Murti & Brahma Ratha',
    category: 'FESTIVAL_EVENT',
    isActive: true,
    isSpecialEvent: true,
    periodLabel: 'Annual Chaitra Utsava (April)',
    budgetEstimated: 3500000,
    description: 'Sacred Chariot procession, flower decoration, Teppotsava and Vahana sevas',
  },
  {
    id: 'seva-shravana',
    code: 'EVT-SR-01',
    name: 'Shravana Masa Special Pooja Series 2025',
    defaultAmount: 1001,
    deity: 'Lord Shiva & Sanctum',
    category: 'FESTIVAL_EVENT',
    isActive: true,
    isSpecialEvent: true,
    periodLabel: 'Shravana Month (Jul / Aug)',
    budgetEstimated: 800000,
    description: 'Month-long Bilvarchana, special evening deepotsava, and Sahasranama chanting',
  },

  // 2. Annadanam & Prasadam Events
  {
    id: 'seva-5',
    code: 'SV-AN-01',
    name: 'Nitya Annadanam (One Day Prasadam Sponsor)',
    defaultAmount: 5001,
    deity: 'Annapurna Mata',
    category: 'ANNADANAM',
    isActive: true,
    periodLabel: 'Daily / Year-Round',
    budgetEstimated: 1800000,
    description: 'Sacred midday meal served to hundreds of visiting devotees daily',
  },
  {
    id: 'seva-9',
    code: 'SV-GO-01',
    name: 'Go Seva & Goshala Fodder Fund',
    defaultAmount: 501,
    deity: 'Kamadhenu Goshala',
    category: 'ANNADANAM',
    isActive: true,
    periodLabel: 'Daily / Year-Round',
    budgetEstimated: 400000,
    description: 'Fodder, veterinary care, and upkeep for sacred temple cows',
  },

  // 3. Capital Renovation & Temple Infrastructure Projects
  {
    id: 'seva-7',
    code: 'PRJ-RN-01',
    name: 'Rajagopuram & Sanctum Renovation Project',
    defaultAmount: 21000,
    deity: 'Temple Trust / Sannidhi',
    category: 'BUILDING_FUND',
    isActive: true,
    isSpecialEvent: true,
    periodLabel: 'Ongoing Capital Drive 2025-27',
    budgetEstimated: 5000000,
    description: 'Grand entrance tower construction, gold kalasha gilding & sanctum stonework',
  },

  // 4. Daily Sanctum Poojas & Archana
  {
    id: 'seva-1',
    code: 'SV-01',
    name: 'Archana & Deeparadhana',
    defaultAmount: 51,
    deity: 'Main Sanctum',
    category: 'DAILY_SEVA',
    isActive: true,
    periodLabel: 'Daily Sanctum',
    description: 'Ashtottara Shatanamavali archana with sacred camphor aarti',
  },
  {
    id: 'seva-2',
    code: 'SV-02',
    name: 'Sahasranama Archana',
    defaultAmount: 101,
    deity: 'Lord Lakshmi Narayana',
    category: 'DAILY_SEVA',
    isActive: true,
    periodLabel: 'Daily Sanctum',
    description: 'Recitation of 1,000 holy names with flower offering and kumkuma prasadam',
  },
  {
    id: 'seva-3',
    code: 'SV-03',
    name: 'Maha Rudrabhishekam / Ksheerabhishekam',
    defaultAmount: 501,
    deity: 'Lord Shiva / Sanctum',
    category: 'SPECIAL_POOJA',
    isActive: true,
    periodLabel: 'Morning Abhisheka Time',
    description: 'Panchamrita and holy Ganga jal abhishekam with Namaka Chamaka chanting',
  },
  {
    id: 'seva-4',
    code: 'SV-04',
    name: 'Satyanarayana Swamy Pooja',
    defaultAmount: 1100,
    deity: 'Lord Satyanarayana',
    category: 'SPECIAL_POOJA',
    isActive: true,
    periodLabel: 'Pournami & Auspicious Days',
    description: 'Full katha recitation with five chapters, sapadha prasadam & vastra daan',
  },
  {
    id: 'seva-8',
    code: 'SV-08',
    name: 'Samanya Danam (General Devotee Fund)',
    defaultAmount: 251,
    deity: 'General Fund',
    category: 'DAILY_SEVA',
    isActive: true,
    periodLabel: 'General',
    description: 'Unrestricted devotee contribution towards regular temple operational expenses',
  },

  // 5. Perpetual Endowments
  {
    id: 'seva-6',
    code: 'SV-06',
    name: 'Shashwatha Pooja (Perpetual Endowment)',
    defaultAmount: 11000,
    deity: 'All Deities',
    category: 'SPECIAL_POOJA',
    isActive: true,
    periodLabel: 'Life-Time / Annual Recurring',
    budgetEstimated: 1200000,
    description: 'Fixed deposit corpus offering pooja on devotee birthday / anniversary forever',
  },

  // 6. In-Kind Offerings
  {
    id: 'seva-10',
    code: 'SV-10',
    name: 'Dravya Daan (In-Kind Gold / Silver / Groceries)',
    defaultAmount: 0,
    deity: 'Temple Store',
    category: 'IN_KIND',
    isActive: true,
    periodLabel: 'As Received',
    description: 'Physical commodities offered for sanctum rituals or community kitchen',
  },
];

export const DEFAULT_CHART_OF_ACCOUNTS: Account[] = [
  // Assets (1000s)
  {
    id: 'acc-101',
    code: '1010',
    name: 'In-Hand Cash',
    category: 'ASSET',
    subCategory: 'Cash & Bank',
    balance: 50000,
    isSystem: true,
    description: 'Physical cash held in temple counter and cash box',
  },
  {
    id: 'acc-103',
    code: '1020',
    name: 'State Bank of India (Main Operational & UPI)',
    category: 'ASSET',
    subCategory: 'Cash & Bank',
    balance: 250000,
    isSystem: true,
    description: 'Main operational bank account for daily sevas and counter UPI receipts',
  },
  {
    id: 'acc-104',
    code: '1025',
    name: 'Canara Bank (Corpus & Building Fund)',
    category: 'ASSET',
    subCategory: 'Cash & Bank',
    balance: 500000,
    isSystem: true,
    description: 'Dedicated bank account for temple construction, corpus donations and cheques',
  },
  {
    id: 'acc-105',
    code: '1030',
    name: 'Fixed Deposits (FD)',
    category: 'ASSET',
    subCategory: 'Investments',
    balance: 1000000,
    isSystem: false,
    description: 'Bank term deposits and corpus investment',
  },

  // Liabilities & Capital (2000s)
  {
    id: 'acc-201',
    code: '2010',
    name: 'Corpus & Temple Fund',
    category: 'LIABILITY',
    subCategory: 'Capital Funds',
    balance: 1800000,
    isSystem: true,
    description: 'Permanent capital endowment fund of the temple',
  },

  // Income (3000s)
  {
    id: 'acc-302',
    code: '3010',
    name: 'Seva & Devotee Offerings',
    category: 'INCOME',
    subCategory: 'Direct Income',
    balance: 0,
    isSystem: true,
    description: 'Receipts from daily sevas, special poojas, and festival events',
  },
  {
    id: 'acc-301',
    code: '3020',
    name: 'Hundi / Danam Collections',
    category: 'INCOME',
    subCategory: 'Direct Income',
    balance: 0,
    isSystem: true,
    description: 'Collections from hundi, donation boxes, and general contributions',
  },

  // Expenses (4000s)
  {
    id: 'acc-401',
    code: '4010',
    name: 'Ritual & Pooja Expenses',
    category: 'EXPENSE',
    subCategory: 'Direct Expense',
    balance: 0,
    isSystem: true,
    isActive: true,
    description: 'Priest dakshina, flowers, camphor, oil, and pooja consumables',
  },
  {
    id: 'acc-403',
    code: '4020',
    name: 'Annadanam & Prasadam',
    category: 'EXPENSE',
    subCategory: 'Direct Expense',
    balance: 0,
    isSystem: false,
    isActive: true,
    description: 'Groceries, rice, vegetables, and provisions for devotee feeding',
  },
  {
    id: 'acc-402',
    code: '4030',
    name: 'Temple Maintenance & Utilities',
    category: 'EXPENSE',
    subCategory: 'Administrative Expense',
    balance: 0,
    isSystem: false,
    isActive: true,
    description: 'Electricity, cleaning, staff honorarium, and repairs',
  },
];

export const DEFAULT_TEMPLE_ASSETS: TempleAsset[] = [
  {
    id: 'ast-1',
    code: 'JWL-01',
    name: '22K Gold Deity Kireetam (Swarna Makuta)',
    category: 'SACRED_JEWELRY',
    assignedDeity: 'Lord Lakshmi Narayana',
    metalPurity: '22K Gold (916 KDM)',
    grossWeightGrams: 520,
    netWeightGrams: 485,
    valuation: 3650000,
    location: 'Strongroom Vault Locker #1',
    custodyStatus: 'IN_VAULT',
    currentCustodian: 'Pt. Raghavendra Dixit (Chief Archaka)',
    acquisitionDate: '2019-04-14',
    sourceOfAcquisition: 'DONATION',
    donorName: 'Smt. Rukmini & Family',
    condition: 'EXCELLENT',
    notes: 'Studded with Navaratna precious gemstones. Used exclusively during Brahmotsavam & Vaikunta Ekadashi.',
    isSynced: false,
  },
  {
    id: 'ast-2',
    code: 'JWL-02',
    name: '92.5 Sterling Silver Chhatra & Prabhavali',
    category: 'SACRED_JEWELRY',
    assignedDeity: 'Lord Lakshmi Narayana (Main Sanctum)',
    metalPurity: '92.5 Sterling Silver',
    grossWeightGrams: 4500,
    netWeightGrams: 4500,
    valuation: 420000,
    location: 'Main Sanctum (Garbhagriha)',
    custodyStatus: 'IN_SANCTUM',
    currentCustodian: 'Ramesh Shastri (Priest)',
    acquisitionDate: '2020-11-25',
    sourceOfAcquisition: 'DONATION',
    donorName: 'Shri Ramachandra Trust',
    condition: 'GOOD',
    notes: 'Mounted above the presiding deity Vigraha in the Garbhagriha.',
    isSynced: false,
  },
  {
    id: 'ast-3',
    code: 'LND-01',
    name: 'Temple Sacred Complex & Sanctum Land',
    category: 'LAND_PROPERTY',
    surveyNo: 'Sy. No. 142/2A',
    areaDescription: '2.50 Acres',
    locationAddress: 'Sanatana Nagar, Bengaluru - 560085',
    valuation: 12500000,
    location: 'Temple Main Campus',
    custodyStatus: 'ACTIVE_USE',
    currentCustodian: 'Board of Trustees',
    acquisitionDate: '2015-01-01',
    sourceOfAcquisition: 'ANCIENT_HERITAGE',
    condition: 'EXCELLENT',
    notes: 'Registered in the name of the Temple Charitable Trust with clear Patta/Khata title.',
    isSynced: false,
  },
  {
    id: 'ast-4',
    code: 'LND-02',
    name: 'Temple Outer Commercial Shops (4 Units)',
    category: 'LAND_PROPERTY',
    surveyNo: 'Sy. No. 142/2B',
    areaDescription: '1,600 Sq. Ft. Built-up',
    locationAddress: 'North Gate, Temple Car Street',
    tenantName: 'Shri Balaji Pooja Samagri & Flowers (Shop 1-4)',
    monthlyRentAmount: 32000,
    valuation: 3500000,
    location: 'Temple Outer Periphery',
    custodyStatus: 'ACTIVE_USE',
    currentCustodian: 'Srinivasan Iyer (Accountant)',
    acquisitionDate: '2021-03-10',
    sourceOfAcquisition: 'TEMPLE_PURCHASE',
    condition: 'GOOD',
    notes: 'Yields ₹32,000 monthly rental revenue credited to Temple Income Account (acc-305).',
    isSynced: false,
  },
  {
    id: 'ast-5',
    code: 'EQ-01',
    name: 'Carved Teakwood & Brass Garuda Vahana',
    category: 'SANCTUM_EQUIPMENT',
    assignedDeity: 'Lord Lakshmi Narayana (Utsava Murti)',
    valuation: 280000,
    location: 'Vahana Mandapam',
    custodyStatus: 'ACTIVE_USE',
    currentCustodian: 'Temple Maintenance In-charge',
    acquisitionDate: '2018-08-15',
    sourceOfAcquisition: 'DONATION',
    donorName: 'Devotees Association',
    condition: 'GOOD',
    notes: 'Used for procession on Saturday evenings and annual Brahmotsavam.',
    isSynced: false,
  },
  {
    id: 'ast-6',
    code: 'EQ-02',
    name: 'Heavy Brass Annadanam Cooking Cauldrons (Set of 6)',
    category: 'KITCHEN_INVENTORY',
    assignedDeity: 'Annapurna Kitchen',
    valuation: 150000,
    location: 'Temple Mega Kitchen / Bhandara',
    custodyStatus: 'ACTIVE_USE',
    currentCustodian: 'Chief Kitchen Supervisor',
    acquisitionDate: '2022-05-18',
    sourceOfAcquisition: 'TEMPLE_PURCHASE',
    condition: 'GOOD',
    notes: 'Capacity to cook for 1,500 devotees daily during Nitya Annadanam.',
    isSynced: false,
  },
  {
    id: 'ast-7',
    code: 'COW-01',
    name: 'Desi Gir Cow (Kamadhenu) & Calf',
    category: 'GOSHALA_CATTLE',
    assignedDeity: 'Sanctum Go-Pooja',
    valuation: 95000,
    location: 'Temple Goshala Yard',
    custodyStatus: 'ACTIVE_USE',
    currentCustodian: 'Goshala Caretaker',
    acquisitionDate: '2023-01-14',
    sourceOfAcquisition: 'DONATION',
    donorName: 'Shri Anand Kumar',
    condition: 'EXCELLENT',
    notes: 'Provides pure cow milk for deity Nitya Ksheerabhishekam and Sanctum ghee lamps.',
    isSynced: false,
  },
];


export const DEFAULT_EVENTS: TempleEvent[] = DEFAULT_SEVA_TYPES.map(s => ({
  id: s.id,
  code: s.code,
  name: s.name,
  financialYear: '2025-2026',
  startDate: '2025-04-01',
  endDate: '2026-03-31',
  description: s.description || s.name,
  status: 'ACTIVE' as const,
  budgetEstimated: s.budgetEstimated || 1000000,
  totalCollected: 0,
  totalSpent: 0,
  isDefault: s.category === 'DAILY_SEVA'
}));

export const DEFAULT_FINANCIAL_YEARS: FinancialYearPeriod[] = [
  {
    id: 'fy-2024-25',
    label: '2024-2025',
    startDate: '2024-04-01',
    endDate: '2025-03-31',
    isCurrent: false,
    isAuditLocked: true,
    auditedDate: '2025-05-18',
    auditorName: 'CA Raghavendra Rao & Associates',
    auditorRegistrationNo: 'ICAI-M-209844',
    notes: 'Statutory audit completed and certified without qualifications. All receipts reconciled with bank passbooks.',
    openingBalances: [
      { id: 'src-prev-1', type: 'CASH', sourceName: 'Sanctum Strongroom Cash Safe', openingAmount: 32000, closingAmount: 45200, auditedAmount: 45200 },
      { id: 'src-prev-2', type: 'CASH', sourceName: 'Counter Float Cash', openingAmount: 10000, closingAmount: 12000, auditedAmount: 12000 },
      { id: 'src-prev-3', type: 'BANK', sourceName: 'State Bank of India (Current A/C #38992019482)', bankName: 'SBI', accountNumber: '38992019482', openingAmount: 340000, closingAmount: 485000, auditedAmount: 485000 },
      { id: 'src-prev-4', type: 'BANK', sourceName: 'Canara Bank (Savings Corpus #1092840192)', bankName: 'Canara Bank', accountNumber: '1092840192', openingAmount: 980000, closingAmount: 1250000, auditedAmount: 1250000 },
      { id: 'src-prev-5', type: 'FIXED_DEPOSIT', sourceName: '3-Year Temple Endowment Term Deposit', bankName: 'SBI', accountNumber: 'FD-8812', openingAmount: 2000000, closingAmount: 2500000, auditedAmount: 2500000 }
    ],
    closingBalances: [
      { id: 'src-prev-1', type: 'CASH', sourceName: 'Sanctum Strongroom Cash Safe', openingAmount: 32000, closingAmount: 45200, auditedAmount: 45200 },
      { id: 'src-prev-2', type: 'CASH', sourceName: 'Counter Float Cash', openingAmount: 10000, closingAmount: 12000, auditedAmount: 12000 },
      { id: 'src-prev-3', type: 'BANK', sourceName: 'State Bank of India (Current A/C #38992019482)', bankName: 'SBI', accountNumber: '38992019482', openingAmount: 340000, closingAmount: 485000, auditedAmount: 485000 },
      { id: 'src-prev-4', type: 'BANK', sourceName: 'Canara Bank (Savings Corpus #1092840192)', bankName: 'Canara Bank', accountNumber: '1092840192', openingAmount: 980000, closingAmount: 1250000, auditedAmount: 1250000 },
      { id: 'src-prev-5', type: 'FIXED_DEPOSIT', sourceName: '3-Year Temple Endowment Term Deposit', bankName: 'SBI', accountNumber: 'FD-8812', openingAmount: 2000000, closingAmount: 2500000, auditedAmount: 2500000 }
    ]
  },
  {
    id: 'fy-2025-26',
    label: '2025-2026',
    startDate: '2025-04-01',
    endDate: '2026-03-31',
    isCurrent: true,
    isAuditLocked: false,
    notes: 'Active financial operating period. Opening balances rolled over from audited FY 2024-25.',
    openingBalances: [
      { id: 'src-1', type: 'CASH', sourceName: 'Sanctum Strongroom Cash Safe', openingAmount: 45200, notes: 'Physical cash in temple double-lock vault' },
      { id: 'src-2', type: 'CASH', sourceName: 'Counter Operating Cash Float', openingAmount: 12000, notes: 'Drawer float for daily change' },
      { id: 'src-3', type: 'BANK', sourceName: 'State Bank of India (Current A/C #38992019482)', bankName: 'State Bank of India', accountNumber: '38992019482', openingAmount: 485000, notes: 'Daily seva and UPI collection account' },
      { id: 'src-4', type: 'BANK', sourceName: 'Canara Bank (Savings Corpus #1092840192)', bankName: 'Canara Bank', accountNumber: '1092840192', openingAmount: 1250000, notes: 'Dedicated temple corpus savings account' },
      { id: 'src-5', type: 'FIXED_DEPOSIT', sourceName: '3-Year Temple Endowment Term Deposit', bankName: 'State Bank of India', accountNumber: 'FD-8812', openingAmount: 2500000, notes: 'Auto-renewing 7.1% interest term deposit' },
      { id: 'src-6', type: 'OTHER', sourceName: 'Postal Savings Certificate & Stamp Float', openingAmount: 15000, notes: 'Post office passbook for emergency telegraphic sanctions' }
    ]
  },
  {
    id: 'fy-2026-27',
    label: '2026-2027',
    startDate: '2026-04-01',
    endDate: '2027-03-31',
    isCurrent: false,
    isAuditLocked: false,
    notes: 'Upcoming financial year. Opening balances will be populated automatically upon FY 2025-26 audit closure.',
    openingBalances: []
  }
];
